### ISSUE TITLE
Docker - python-agent_1 error

### ISSUE THREAD

**Issue by compunerd4** [adityathebe/telegramForwarder#19]
I've just installed docker, cloned the repo and ran docket-compose up. 
It ran successfully and my bot is working to the point that I can add all my redirections and filters.

As soon as any messages come onto the channels that I am in, this error comes up and nothing is redirected.

`python-agent_1  | [INFO] forwarder.py:26 -- Channel Message Received
python-agent_1  | [INFO] forwarder.py:40 -- Message :xxxxxxxxxxxxxxxxxxxx
python-agent_1  | [INFO] forwarder.py:41 -- Sender : 1xxxxxx
python-agent_1  | [ERROR] updates.py:459 -- Unhandled exception on forwarder_event_handler
python-agent_1  | Traceback (most recent call last):
python-agent_1  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
python-agent_1  |     await callback(event)
python-agent_1  |   File "/telegram-python-agent/forwarder.py", line 44, in forwarder_event_handler
python-agent_1  |     user_entity = await telegram_client.get_input_entity(sender_id)
python-agent_1  |   File "/usr/local/lib/python3.8/site-packages/telethon/client/users.py", line 442, in get_input_entity
python-agent_1  |     raise ValueError(
python-agent_1  | ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f8011974f70>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
`

I don't have any conflicting versions of the postgres running. I'm not sure why this message is happening.

Every time a message comes up in any channel (not only the ones in my redirects) this error comes up.

**Comment by compunerd4** [comment]
complete reinstall fixed
